# Database connection
# Note: Use 'sa' as the username for the SQL Server instance
spring.datasource.url=jdbc:sqlserver://localhost1433;databaseName=StudentRegistrationPortal_DB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Vijaysql@16
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings
# 'update' will automatically create your tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server port
server.port=8081
